apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vgq6cue63-go
  janus-idp.io/tekton: vgq6cue63-go
  backstage.io/kubernetes-id: vgq6cue63-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vgq6cue63-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
